In [1]:
import numpy as np
import pandas as pd
from lazypredict.lazypredict.Supervised import LazyClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.svm import SVC
from sklearn import metrics
import pickle

In [2]:
data = pd.read_csv("data/iris.csv")

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1           5.10          3.50           1.40          0.20  Iris-setosa
1   2           4.90          3.00           1.40          0.20  Iris-setosa
2   3           4.70          3.20           1.30          0.20  Iris-setosa
3   4           4.60          3.10           1.50          0.20  Iris-setosa
4   5           5.00          3.60           1.40          0.20  Iris-setosa

In [26]:
data.sample(5)

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
44    45           5.10          3.80           1.90          0.40   
1      2           4.90          3.00           1.40          0.20   
62    63           6.00          2.20           4.00          1.00   
114  115           5.80          2.80           5.10          2.40   
22    23           4.60          3.60           1.00          0.20   

             Species  
44       Iris-setosa  
1        Iris-setosa  
62   Iris-versicolor  
114   Iris-virginica  
22       Iris-setosa

In [5]:
data['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [6]:
X = data.drop(['Id','Species'], axis=1)
y = data['Species']

In [7]:
le = LabelEncoder()
y = le.fit_transform(data['Species'])

In [8]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [9]:
X_train, X_test, y_train, y_test = train_test_split(X,y , test_size = 0.2, stratify=data['Species'])

In [10]:
clf = LazyClassifier(verbose=0, ignore_warnings=True)
models, predictions = clf.fit(X_train, X_test, y_train, y_test)

100%|██████████████████████████████████████████████████████████████████████████████████| 29/29 [00:00<00:00, 48.07it/s]

[23:36:12] WARNING: C:/Users/Administrator/workspace/xgboost-win64_release_1.5.1/src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'multi:softprob' was changed from 'merror' to 'mlogloss'. Explicitly set eval_metric if you'd like to restore the old behavior.


In [11]:
print(models)

                               Accuracy  Balanced Accuracy ROC AUC  F1 Score  \
Model                                                                          
SGDClassifier                      1.00               1.00    None      1.00   
QuadraticDiscriminantAnalysis      1.00               1.00    None      1.00   
LinearDiscriminantAnalysis         1.00               1.00    None      1.00   
LinearSVC                          0.97               0.97    None      0.97   
LabelSpreading                     0.97               0.97    None      0.97   
XGBClassifier                      0.97               0.97    None      0.97   
RandomForestClassifier             0.97               0.97    None      0.97   
NuSVC                              0.97               0.97    None      0.97   
LogisticRegression                 0.97               0.97    None      0.97   
BaggingClassifier                  0.97               0.97    None      0.97   
LGBMClassifier                     0.97 

In [12]:
svc = SVC()
svc.fit(X_train, y_train)
y_pred = svc.predict(X_test)

In [13]:
metrics.accuracy_score(y_test, y_pred)

0.9666666666666667

In [14]:
metrics.precision_score(y_test, y_pred, average='micro')

0.9666666666666667

In [15]:
metrics.recall_score(y_test, y_pred, average='micro')

0.9666666666666667

In [16]:
metrics.confusion_matrix(y_test, y_pred)

array([[10,  0,  0],
       [ 0,  9,  1],
       [ 0,  0, 10]], dtype=int64)

In [17]:
svc.predict([[1,2,3,4]])

array([2])

In [18]:
pickle.dump(svc, open("model.pkl", "wb"))

In [19]:
model = pickle.load(open('model.pkl', 'rb'))

In [20]:
model.predict([[5.10, 3.50, 1.40, 0.20]])

array([0])

In [21]:
import flask

In [22]:
flask.__version__

'1.1.2'

In [23]:
np.__version__

'1.20.3'

In [24]:
import sklearn

In [25]:
sklearn.__version__

'0.24.2'